package com.prod.bean;

public class Component {
    /**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column component.id
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column component.name
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column component.prod_typeid
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	private Integer prodTypeid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column component.producer
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	private String producer;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column component.address
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	private String address;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column component.price
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	private Long price;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column component.code
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	private String code;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column component.id
	 * @return  the value of component.id
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column component.id
	 * @param id  the value for component.id
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column component.name
	 * @return  the value of component.name
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column component.name
	 * @param name  the value for component.name
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column component.prod_typeid
	 * @return  the value of component.prod_typeid
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public Integer getProdTypeid() {
		return prodTypeid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column component.prod_typeid
	 * @param prodTypeid  the value for component.prod_typeid
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public void setProdTypeid(Integer prodTypeid) {
		this.prodTypeid = prodTypeid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column component.producer
	 * @return  the value of component.producer
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public String getProducer() {
		return producer;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column component.producer
	 * @param producer  the value for component.producer
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public void setProducer(String producer) {
		this.producer = producer;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column component.address
	 * @return  the value of component.address
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column component.address
	 * @param address  the value for component.address
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column component.price
	 * @return  the value of component.price
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public Long getPrice() {
		return price;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column component.price
	 * @param price  the value for component.price
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public void setPrice(Long price) {
		this.price = price;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column component.code
	 * @return  the value of component.code
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column component.code
	 * @param code  the value for component.code
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public void setCode(String code) {
		this.code = code;
	}

	private Type type;
    
    public Type getType() {
		return type;
	}

	public void setType(Type type) {
		this.type = type;
	}
}