package com.prod.bean;

public class Prod {
    /**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column prod.id
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column prod.typeid
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	private Integer typeid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column prod.name
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column prod.producer
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	private String producer;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column prod.address
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	private String address;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column prod.price
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	private Long price;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column prod.code
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	private String code;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column prod.id
	 * @return  the value of prod.id
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column prod.id
	 * @param id  the value for prod.id
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column prod.typeid
	 * @return  the value of prod.typeid
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public Integer getTypeid() {
		return typeid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column prod.typeid
	 * @param typeid  the value for prod.typeid
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public void setTypeid(Integer typeid) {
		this.typeid = typeid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column prod.name
	 * @return  the value of prod.name
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column prod.name
	 * @param name  the value for prod.name
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column prod.producer
	 * @return  the value of prod.producer
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public String getProducer() {
		return producer;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column prod.producer
	 * @param producer  the value for prod.producer
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public void setProducer(String producer) {
		this.producer = producer;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column prod.address
	 * @return  the value of prod.address
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column prod.address
	 * @param address  the value for prod.address
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column prod.price
	 * @return  the value of prod.price
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public Long getPrice() {
		return price;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column prod.price
	 * @param price  the value for prod.price
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public void setPrice(Long price) {
		this.price = price;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column prod.code
	 * @return  the value of prod.code
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column prod.code
	 * @param code  the value for prod.code
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public void setCode(String code) {
		this.code = code;
	}

	private Type type;
    
    public Type getType() {
		return type;
	}

	public void setType(Type type) {
		this.type = type;
	}
}