package com.prod.bean;

public class Type {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column type.id
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column type.name
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	private String name;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column type.id
	 * @return  the value of type.id
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column type.id
	 * @param id  the value for type.id
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column type.name
	 * @return  the value of type.name
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column type.name
	 * @param name  the value for type.name
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}
}