package com.prod.dao;

import com.prod.bean.Component;
import com.prod.bean.ComponentExample;
import java.util.List;

public interface ComponentDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table component
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	int countByExample(ComponentExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table component
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	int deleteByExample(ComponentExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table component
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table component
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	void insert(Component record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table component
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	void insertSelective(Component record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table component
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	List selectByExample(ComponentExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table component
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	Component selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table component
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	int updateByExampleSelective(Component record, ComponentExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table component
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	int updateByExample(Component record, ComponentExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table component
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	int updateByPrimaryKeySelective(Component record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table component
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	int updateByPrimaryKey(Component record);
}