package com.prod.dao;

import com.prod.bean.Type;
import com.prod.bean.TypeExample;
import java.util.List;

public interface TypeDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table type
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	int countByExample(TypeExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table type
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	int deleteByExample(TypeExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table type
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table type
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	void insert(Type record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table type
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	void insertSelective(Type record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table type
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	List selectByExample(TypeExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table type
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	Type selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table type
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	int updateByExampleSelective(Type record, TypeExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table type
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	int updateByExample(Type record, TypeExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table type
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	int updateByPrimaryKeySelective(Type record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table type
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	int updateByPrimaryKey(Type record);
}