package com.prod.dao.impl;

import com.prod.bean.Component;
import com.prod.bean.ComponentExample;
import com.prod.dao.ComponentDAO;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ComponentDAOImpl extends SqlMapClientDaoSupport implements ComponentDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table component
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public ComponentDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table component
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public int countByExample(ComponentExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"component.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table component
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public int deleteByExample(ComponentExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"component.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table component
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public int deleteByPrimaryKey(Integer id) {
		Component key = new Component();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"component.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table component
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public void insert(Component record) {
		getSqlMapClientTemplate().insert("component.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table component
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public void insertSelective(Component record) {
		getSqlMapClientTemplate().insert(
				"component.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table component
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public List selectByExample(ComponentExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"component.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table component
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public Component selectByPrimaryKey(Integer id) {
		Component key = new Component();
		key.setId(id);
		Component record = (Component) getSqlMapClientTemplate()
				.queryForObject("component.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table component
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public int updateByExampleSelective(Component record,
			ComponentExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"component.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table component
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public int updateByExample(Component record, ComponentExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"component.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table component
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public int updateByPrimaryKeySelective(Component record) {
		int rows = getSqlMapClientTemplate()
				.update("component.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table component
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public int updateByPrimaryKey(Component record) {
		int rows = getSqlMapClientTemplate().update(
				"component.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table component
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	private static class UpdateByExampleParms extends ComponentExample {
		private Object record;

		public UpdateByExampleParms(Object record, ComponentExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}