package com.prod.dao.impl;

import com.prod.bean.Type;
import com.prod.bean.TypeExample;
import com.prod.dao.TypeDAO;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TypeDAOImpl extends SqlMapClientDaoSupport implements TypeDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table type
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public TypeDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table type
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public int countByExample(TypeExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"type.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table type
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public int deleteByExample(TypeExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"type.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table type
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public int deleteByPrimaryKey(Integer id) {
		Type key = new Type();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"type.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table type
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public void insert(Type record) {
		getSqlMapClientTemplate().insert("type.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table type
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public void insertSelective(Type record) {
		getSqlMapClientTemplate().insert(
				"type.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table type
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public List selectByExample(TypeExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"type.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table type
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public Type selectByPrimaryKey(Integer id) {
		Type key = new Type();
		key.setId(id);
		Type record = (Type) getSqlMapClientTemplate().queryForObject(
				"type.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table type
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public int updateByExampleSelective(Type record, TypeExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"type.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table type
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public int updateByExample(Type record, TypeExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"type.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table type
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public int updateByPrimaryKeySelective(Type record) {
		int rows = getSqlMapClientTemplate().update(
				"type.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table type
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	public int updateByPrimaryKey(Type record) {
		int rows = getSqlMapClientTemplate().update(
				"type.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table type
	 * @ibatorgenerated  Tue Dec 29 15:51:20 CST 2015
	 */
	private static class UpdateByExampleParms extends TypeExample {
		private Object record;

		public UpdateByExampleParms(Object record, TypeExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}